class Lists {
  static List stateList = <Map>[
    {"value": 0, "text": 'Select State'},
    {"value": 1, "text": 'Abia'},
    {"value": 2, "text": 'Adamawa'},
    {"value": 3, "text": 'Akwa Ibom'},
    {"value": 4, "text": 'Anambra'},
    {"value": 5, "text": 'Bauchi'},
    {"value": 6, "text": 'Bayelsa'},
    {"value": 7, "text": 'Benue'},
    {"value": 8, "text": 'Borno'},
    {"value": 9, "text": 'Cross River'},
    {"value": 10, "text": 'Delta'},
    {"value": 11, "text": 'Ebonyi'},
    {"value": 12, "text": 'Enugu'},
    {"value": 13, "text": 'Edo'},
    {"value": 14, "text": 'Ekiti'},
    {"value": 15, "text": 'Abuja'},
    {"value": 16, "text": 'Gombe'},
    {"value": 17, "text": 'Imo'},
    {"value": 18, "text": 'Jigawa'},
    {"value": 19, "text": 'Kaduna'},
    {"value": 20, "text": 'Kano'},
    {"value": 21, "text": 'Katsina'},
    {"value": 22, "text": 'Kebbi'},
    {"value": 23, "text": 'Kogi'},
    {"value": 24, "text": 'Kogi'},
    {"value": 25, "text": 'Lagos'},
    {"value": 26, "text": 'Nasarawa'},
    {"value": 27, "text": 'Niger'},
    {"value": 28, "text": 'Ogun'},
    {"value": 29, "text": 'Ondo'},
    {"value": 30, "text": 'Osun'},
    {"value": 31, "text": 'Oyo'},
    {"value": 32, "text": 'Plateau'},
    {"value": 33, "text": 'Rivers'},
    {"value": 34, "text": 'Sokoto'},
    {"value": 35, "text": 'Taraba'},
    {"value": 36, "text": 'Yobe'},
    {"value": 37, "text": 'Zamfara'},
  ];

  static List localGovtList = <String>["Local Government"];

  static List phc = <String>["Phc 1"];

  static List vaccines = <String>[
    "Select Vaccine",
    "BCG",
    "HBV 1",
    "OPV",
    "OPV 1",
    "PCV 1",
    "Rotarix 1",
    "Pentavalent 1",
    "OPV 2",
    "Rotarix 2",
    "PCV 2",
    "Pentavalent 2",
    "OPV 3",
    "PCV 3",
    "IPV",
    "Rotarix 3",
    "Pentavalent 3",
    "Vitamin A1",
    "Measles Vaccine",
    "Yellow Fever vaccine",
    "Meningitis vaccine",
    "Vitamin A2",
    "OPV booster",
    "Measles 2",
    "Typhoid Vaccine"
  ];

  static List diseases = <String>[
    "Select Disease",
    "Tuberculosis",
    "Hepatitis",
    "Poliomyelitis",
    "Pneumonia",
    "Diarrhoea",
    "Diphtheria",
    "Tetanus",
    "Pertussis",
    "Hepatitis B",
    "Hemophilus Influenza type B",
    "Poor vision",
    "Measles",
    "Yellow fever",
    "Meningococcal Meningitis",
    "Typhoid",
  ];
}
