class Lists {
  static List stateList = <Map>[
    {"value": 0, "text": 'Select State'},
    {"value": 1, "text": 'Abia'},
    {"value": 2, "text": 'Adamawa'},
    {"value": 3, "text": 'Akwa Ibom'},
    {"value": 4, "text": 'Anambra'},
    {"value": 5, "text": 'Bauchi'},
    {"value": 6, "text": 'Bayelsa'},
    {"value": 7, "text": 'Benue'},
    {"value": 8, "text": 'Borno'},
    {"value": 9, "text": 'Cross River'},
    {"value": 10, "text": 'Delta'},
    {"value": 11, "text": 'Ebonyi'},
    {"value": 12, "text": 'Enugu'},
    {"value": 13, "text": 'Edo'},
    {"value": 14, "text": 'Ekiti'},
    {"value": 15, "text": 'FCT - Abuja'},
    {"value": 16, "text": 'Gombe'},
    {"value": 17, "text": 'Imo'},
    {"value": 18, "text": 'Jigawa'},
    {"value": 19, "text": 'Kaduna'},
    {"value": 20, "text": 'Kano'},
    {"value": 21, "text": 'Katsina'},
    {"value": 22, "text": 'Kebbi'},
    {"value": 23, "text": 'Kogi'},
    {"value": 24, "text": 'Kogi'},
    {"value": 25, "text": 'Lagos'},
    {"value": 26, "text": 'Nasarawa'},
    {"value": 27, "text": 'Niger'},
    {"value": 28, "text": 'Ogun'},
    {"value": 29, "text": 'Ondo'},
    {"value": 30, "text": 'Osun'},
    {"value": 31, "text": 'Oyo'},
    {"value": 32, "text": 'Plateau'},
    {"value": 33, "text": 'Rivers'},
    {"value": 34, "text": 'Sokoto'},
    {"value": 35, "text": 'Taraba'},
    {"value": 36, "text": 'Yobe'},
    {"value": 37, "text": 'Zamfara'},
  ];

  static List localGovtList = <String>["string"];

  List localAbia = [
    {"value": 0, "text": 'Aba North'},
    {"value": 1, "text": 'Aba South'},
    {"value": 2, "text": 'Arochukwu	'},
    {"value": 3, "text": 'Bende'},
    {"value": 4, "text": 'Ikwuano'},
    {"value": 5, "text": 'Isiala Ngwa North'},
    {"value": 6, "text": 'Isiala Ngwa South'},
    {"value": 7, "text": 'Isuikwuato'},
    {"value": 8, "text": 'Obi Ngwa'},
    {"value": 9, "text": 'Ohafia'},
    {"value": 10, "text": 'Osisioma'},
    {"value": 11, "text": 'Ugwunagbo'},
    {"value": 12, "text": 'Ukwa East'},
    {"value": 13, "text": 'Ukwa West'},
    {"value": 14, "text": 'Ukwa West	'},
    {"value": 15, "text": 'Umuahia North'},
    {"value": 16, "text": 'Umuahia North'},
    {"value": 17, "text": 'Umu Nneochi'},
    {"value": 18, "text": 'Obi Ngwa'},
  ];

  List localAdamawa = [
    {"value": 0, "text": 'Demsa'},
    {"value": 1, "text": 'Fufure'},
    {"value": 2, "text": 'Ganye'},
    {"value": 3, "text": 'Gayuk'},
    {"value": 4, "text": 'Gombi'},
    {"value": 5, "text": 'Grie'},
    {"value": 6, "text": 'Hong'},
    {"value": 7, "text": 'Jada'},
    {"value": 8, "text": 'Lamurde'},
    {"value": 9, "text": 'Madagali'},
    {"value": 10, "text": 'Maiha'},
    {"value": 11, "text": 'Mayo Belwa'},
    {"value": 12, "text": 'Michika'},
    {"value": 13, "text": 'Mubi North'},
    {"value": 14, "text": 'Mubi South	'},
    {"value": 15, "text": 'Numan'},
    {"value": 16, "text": 'Shelleng'},
    {"value": 17, "text": 'Song'},
    {"value": 18, "text": 'Toungo'},
    {"value": 19, "text": 'Yola North'},
    {"value": 20, "text": 'Yola South'},
  ];

  List localAkwaIbom = [
    {"value": 0, "text": 'Abak'},
    {"value": 1, "text": 'Eastern Obolo'},
    {"value": 2, "text": 'Eket'},
    {"value": 3, "text": 'Esit Eket'},
    {"value": 4, "text": 'Essien Udim'},
    {"value": 5, "text": 'Etim Ekpo'},
    {"value": 6, "text": 'Etinan'},
    {"value": 7, "text": 'Ibeno'},
    {"value": 8, "text": 'Ibesikpo Asutan'},
    {"value": 9, "text": 'Ibiono-Ibom	'},
    {"value": 10, "text": 'Ika'},
    {"value": 11, "text": 'Ikono'},
    {"value": 12, "text": 'Ikot Abasi'},
    {"value": 13, "text": 'Ikot Ekpene'},
    {"value": 14, "text": 'Ini'},
    {"value": 15, "text": 'Itu'},
    {"value": 16, "text": 'Mbo'},
    {"value": 17, "text": 'Mkpat-Enin	'},
    {"value": 18, "text": 'Nsit-Atai'},
    {"value": 19, "text": 'Nsit-Ibom'},
    {"value": 20, "text": 'Nsit-Ubium'},
    {"value": 21, "text": 'Obot Akara	'},
    {"value": 22, "text": 'Okobo	'},
    {"value": 23, "text": 'Onna	'},
    {"value": 24, "text": 'Oron'},
    {"value": 25, "text": 'Oruk Anam'},
    {"value": 26, "text": 'Udung-Uko'},
    {"value": 27, "text": 'Ukanafun'},
    {"value": 28, "text": 'Uruan'},
    {"value": 29, "text": 'Urue-Offong/Oruko'},
    {"value": 30, "text": 'Uyo'},
    {"value": 31, "text": 'Obot Akara'},
  ];

  List localAnambara = [
    {"value": 0, "text": 'Aguata'},
    {"value": 1, "text": 'Anambra East'},
    {"value": 2, "text": 'Anambra West'},
    {"value": 3, "text": 'Anaocha'},
    {"value": 4, "text": 'Awka North'},
    {"value": 5, "text": 'Awka South'},
    {"value": 6, "text": 'Ayamelum'},
    {"value": 7, "text": 'Dunukofia'},
    {"value": 8, "text": 'Ekwusigo'},
    {"value": 9, "text": 'Idemili North'},
    {"value": 10, "text": 'Idemili South'},
    {"value": 11, "text": 'Ihiala'},
    {"value": 12, "text": 'Njikoka'},
    {"value": 13, "text": 'Nnewi North'},
    {"value": 14, "text": 'Nnewi South'},
    {"value": 15, "text": 'Ogbaru'},
    {"value": 16, "text": 'Onitsha North'},
    {"value": 17, "text": 'Onitsha South'},
    {"value": 18, "text": 'Orumba North'},
    {"value": 19, "text": 'Orumba South'},
    {"value": 20, "text": 'Oyi'},
  ];

  List locaBauchi = [
    {"value": 0, "text": 'Alkaleri'},
    {"value": 1, "text": 'Bauchi'},
    {"value": 2, "text": 'Bogoro'},
    {"value": 3, "text": 'Damban'},
    {"value": 4, "text": 'Darazo'},
    {"value": 5, "text": 'Dass'},
    {"value": 6, "text": 'Gamawa'},
    {"value": 7, "text": 'Ganjuwa'},
    {"value": 8, "text": 'Giade'},
    {"value": 9, "text": 'Itas/Gadau'},
    {"value": 10, "text": 'Jama\'are'},
    {"value": 11, "text": 'Katagum'},
    {"value": 12, "text": 'Kirfi'},
    {"value": 13, "text": 'Misau'},
    {"value": 14, "text": 'Ningi'},
    {"value": 15, "text": 'Shira'},
    {"value": 16, "text": 'Tafawa Balewa'},
    {"value": 17, "text": 'Toro'},
    {"value": 18, "text": 'Warji'},
    {"value": 19, "text": 'Zaki'},
  ];

  List localBayelsa = [
    {"value": 0, "text": 'Brass'},
    {"value": 1, "text": 'Ekeremor'},
    {"value": 2, "text": 'Kolokuma/Opokuma'},
    {"value": 3, "text": 'Nembe'},
    {"value": 4, "text": 'Ogbia'},
    {"value": 5, "text": 'Sagbama'},
    {"value": 6, "text": 'Southern Ijaw'},
    {"value": 7, "text": 'Yenagoa'},
  ];

  List localBenue = [
    {"value": 0, "text": 'Agatu'},
    {"value": 1, "text": 'Apa'},
    {"value": 2, "text": 'Ado'},
    {"value": 3, "text": 'Buruku'},
    {"value": 4, "text": 'Gboko'},
    {"value": 5, "text": 'Guma'},
    {"value": 6, "text": 'Gwer East'},
    {"value": 7, "text": 'Gwer West'},
    {"value": 8, "text": 'Katsina-Ala'},
    {"value": 9, "text": 'Konshisha'},
    {"value": 10, "text": 'Kwande'},
    {"value": 11, "text": 'Logo'},
    {"value": 12, "text": 'Makurdi'},
    {"value": 13, "text": 'Misau'},
    {"value": 14, "text": 'Obi'},
    {"value": 15, "text": 'Ogbadibo'},
    {"value": 16, "text": 'Ohimini'},
    {"value": 17, "text": 'Oju'},
    {"value": 18, "text": 'Okpokwu'},
    {"value": 19, "text": 'Oturkpo'},
    {"value": 20, "text": 'Tarka'},
    {"value": 21, "text": 'Ukum'},
    {"value": 22, "text": 'Ushongo'},
    {"value": 23, "text": 'Vandeikya'},
    {"value": 24, "text": 'Obi'},
  ];

  List localBorno = [
    {"value": 0, "text": 'Abadam'},
    {"value": 1, "text": 'Askira/Uba'},
    {"value": 2, "text": 'Bama'},
    {"value": 3, "text": 'Bayo'},
    {"value": 4, "text": 'Biu'},
    {"value": 5, "text": 'Chibok'},
    {"value": 6, "text": 'Damboa'},
    {"value": 7, "text": 'Damboa'},
    {"value": 8, "text": 'Gubio'},
    {"value": 9, "text": 'Guzamala'},
    {"value": 10, "text": 'Gwuza'},
    {"value": 11, "text": 'Hawul'},
    {"value": 12, "text": 'Jere'},
    {"value": 13, "text": 'Kaga'},
    {"value": 14, "text": 'Kala/Balge'},
    {"value": 15, "text": 'Konduga'},
    {"value": 16, "text": 'Kukawa'},
    {"value": 17, "text": 'Kwaya Kusar'},
    {"value": 18, "text": 'Mafa'},
    {"value": 19, "text": 'Magumeri'},
    {"value": 20, "text": 'Maiduguri'},
    {"value": 21, "text": 'Marte'},
    {"value": 22, "text": 'Mobbar'},
    {"value": 23, "text": 'Monguno'},
    {"value": 24, "text": 'Ngala'},
    {"value": 25, "text": 'Nganzai'},
    {"value": 26, "text": 'Shani'},
  ];

  List localCrossRiver = [
    {"value": 0, "text": 'Abi'},
    {"value": 1, "text": 'Akamkpa'},
    {"value": 2, "text": 'Akpabuyo'},
    {"value": 3, "text": 'Bakassi'},
    {"value": 4, "text": 'Bekwarra'},
    {"value": 5, "text": 'Biase'},
    {"value": 6, "text": 'Boki'},
    {"value": 7, "text": 'Calabar Municipal'},
    {"value": 8, "text": 'Calabar South'},
    {"value": 9, "text": 'Etung'},
    {"value": 10, "text": 'Ikom'},
    {"value": 11, "text": 'Obanliku'},
    {"value": 12, "text": 'Obubra'},
    {"value": 13, "text": 'Obudu'},
    {"value": 14, "text": 'Odukpani'},
    {"value": 15, "text": 'Yakuur'},
    {"value": 16, "text": 'Obubra'},
    {"value": 17, "text": 'Yala'},
  ];

  List localDelta = [
    {"value": 0, "text": 'Aniocha North'},
    {"value": 1, "text": 'Aniocha South'},
    {"value": 2, "text": 'Bomadi'},
    {"value": 3, "text": 'Burutu'},
    {"value": 4, "text": 'Ethiope East'},
    {"value": 5, "text": 'Ethiope West'},
    {"value": 6, "text": 'Ika North East'},
    {"value": 7, "text": 'Ika South'},
    {"value": 8, "text": 'Isoko North'},
    {"value": 9, "text": 'Isoko South'},
    {"value": 10, "text": 'Ndokwa East'},
    {"value": 11, "text": 'Ndokwa West'},
    {"value": 12, "text": 'Okpe'},
    {"value": 13, "text": 'Oshimili North'},
    {"value": 14, "text": 'Oshimili South'},
    {"value": 15, "text": 'Patani'},
    {"value": 16, "text": 'Sapele'},
    {"value": 17, "text": 'Udu'},
    {"value": 18, "text": 'Ughelli North'},
    {"value": 19, "text": 'Ughelli South'},
    {"value": 20, "text": 'Ukwuani'},
    {"value": 21, "text": 'Uvwie'},
    {"value": 22, "text": 'Warri North'},
    {"value": 23, "text": 'Warri South'},
    {"value": 24, "text": 'Warri South West'},
    {"value": 25, "text": 'Abakaliki'},
    {"value": 26, "text": 'Afikpo North'},
    {"value": 27, "text": 'Ukanafun'},
    {"value": 28, "text": 'Uruan'},
    {"value": 29, "text": 'Urue-Offong/Oruko'},
    {"value": 30, "text": 'Uyo'},
    {"value": 31, "text": 'Obot Akara'},
    {"value": 32, "text": 'Plateau'},
    {"value": 33, "text": 'Rivers'},
    {"value": 34, "text": 'Sokoto'},
    {"value": 35, "text": 'Taraba'},
    {"value": 36, "text": 'Yobe'},
    {"value": 37, "text": 'Zamfara'},
  ];

  List localEbonyi = [
    {"value": 0, "text": 'Aniocha North'},
    {"value": 1, "text": 'Aniocha South'},
    {"value": 2, "text": 'Bomadi'},
    {"value": 3, "text": 'Burutu'},
    {"value": 4, "text": 'Ethiope East'},
    {"value": 5, "text": 'Ethiope West'},
    {"value": 6, "text": 'Ika North East'},
    {"value": 7, "text": 'Ika South'},
    {"value": 8, "text": 'Isoko North'},
    {"value": 9, "text": 'Isoko South'},
    {"value": 10, "text": 'Ndokwa East'},
    {"value": 11, "text": 'Ndokwa West'},
    {"value": 12, "text": 'Okpe'},
    {"value": 13, "text": 'Oshimili North'},
    {"value": 14, "text": 'Oshimili South'},
    {"value": 15, "text": 'Patani'},
    {"value": 16, "text": 'Sapele'},
    {"value": 17, "text": 'Udu'},
    {"value": 18, "text": 'Ughelli North'},
    {"value": 19, "text": 'Ughelli South'},
    {"value": 20, "text": 'Ukwuani'},
    {"value": 21, "text": 'Uvwie'},
    {"value": 22, "text": 'Warri North'},
    {"value": 23, "text": 'Warri South'},
    {"value": 24, "text": 'Warri South West'},
    {"value": 25, "text": 'Abakaliki'},
    {"value": 26, "text": 'Afikpo North'},
    {"value": 27, "text": 'Ukanafun'},
    {"value": 28, "text": 'Uruan'},
    {"value": 29, "text": 'Urue-Offong/Oruko'},
    {"value": 30, "text": 'Uyo'},
    {"value": 31, "text": 'Obot Akara'},
    {"value": 32, "text": 'Plateau'},
    {"value": 33, "text": 'Rivers'},
    {"value": 34, "text": 'Sokoto'},
    {"value": 35, "text": 'Taraba'},
    {"value": 36, "text": 'Yobe'},
    {"value": 37, "text": 'Zamfara'},
  ];
}
